# Nombre de la aplicaci�n para identificarla en Grafana
spring.application.name=App-Monitoreo-G04

# Exponer los puntos de datos (Actuator)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Formatear la salida de m�tricas para Prometheus
management.metrics.tags.application=${spring.application.name}